
/* 
  NOTE: The application logic has been moved entirely to index.html 
  to ensure compatibility with GitHub Pages and avoid build/compilation issues.
  
  This file is kept only for archival purposes.
  Do not edit this file. Edit index.html directly.
*/
